#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
# Redirect output to stderr.
exec 1>&2

IS_ERROR=0
# コミットされるファイルのうち、.phpで終わるもの
FILES=`git diff-index --name-status $against | grep -E '*(.php|.css)$' | cut -c3-`

for FILE in $FILES
do

    ./vendor/bin/phpcbf --standard=wordpress $FILE

    if ! ./vendor/bin/phpcs --standard=wordpress $FILE ; then
        ./vendor/bin/phpcs --standard=wordpress $FILE
        IS_ERROR=1
    else
        git add $FILE
    fi

done

exit $IS_ERROR
