#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
# Redirect output to stderr.
exec 1>&2

IS_ERROR=0
# コミットされるファイルのうち、.phpで終わるもの
for FILE in `git diff-index --name-status $against -- | grep -E '^[AUM].*\(.css|.php)$'| cut -c3-`; do

        wpcs/vendor/bin/phpcbf --standard=wordpress $FILE
        wpcs/vendor/bin/phpcs --standard=wordpress $FILE
        #git add $FILE

done

exit $IS_ERRORs
