language: php

php: '5.6'
php: '7.1'

branches:
  only:
    - master

before_script:
    #@link https://github.com/Automattic/_s/blob/master/.travis.yml
    - export SNIFFS_DIR=/tmp/sniffs
    - composer install --dev
    - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
    - vendor/bin/phpcs --config-set installed_paths $SNIFFS_DIR
    # check javascript
    - npm install -g jscs
    # @link http://jshint.com/docs/
    - npm install -g jshint
    # Pull in the WP Core jshint rules.
    - wget https://develop.svn.wordpress.org/trunk/.jshintrc
script:
    - jshint .
    # Search for PHP syntax errors.
    - find . components/ -name "*.php" -maxdepth 1 -exec php -lf {} \;
    - find . components/ -name "*.php" -maxdepth 1 -exec ./vendor/bin/phpcs -p -s -v {} --standard=wordpress \;
    - find . components/ -name "*.css" -maxdepth 1 -exec ./vendor/bin/phpcs -p -s -v {} --standard=wordpress \;

after_success:
    - set -e::;
    #Only Push origin
    - if [[ "false" != "$TRAVIS_PULL_REQUEST" ]]; then echo "Not deploying pull requests." ; exit ; fi
    #only master branch
    - if [[ "master" != "$TRAVIS_BRANCH" ]]; then echo "Not on the 'master' branch." ; exit ; fi
    #fetch temporary origin
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch
    #make pre-lerease branch and remove for development tools.
    - git checkout -b pre-release remotes/origin/master
    - git rm -rf stylus
    - git rm -fr git-hooks
    - git rm -f .gitignore
    - git rm -f .travis.yml
    - git rm -f README.md
    - git rm -f package.json
    - git rm -f style.css.map
    - git rm -f editor-style.css.map
    - git rm -f fonts/icomoon.zip
    - git rm -f phpcbf-all.sh
    - git rm -f phpmd-all.sh
    - git rm -f composer.*
    - git commit -m "prepare release"
    #marge release for deployment autumnsky.sakura.ne.jp
    - git checkout -b release remotes/origin/release
    - git merge pre-release -m "Travis build release $TRAVIS_COMMIT"
    - git push https://${GH_TOKEN}@github.com/akiya64/shirohanada release

env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=autumnsky64@gmail.com
  - GIT_AUTHOR_NAME=akiya64-in-travis
  - GIT_AUTHOR_EMAIL=autumnsky64@gmail.com
  - secure: "WNm1gaTm7W5poik7AXFMsdZmXmbFDK1SRt7bi58k4LwFnnKlvvtW3w5s16RhiukWjKA5S6tQ8EWfdr2hoIKEMPRfI7/sJamIOo2/NYZeczQnJBDd6b0JTuO0jjjP/XgEbatMQr11Nz9hwQN5iY2gcBYE48bdL+XsHExdujdOcBsl8ERkdafUvS2+O3FUiAZR7+GLQ/ngdb8JzxCqg2c/wzczRz1q7Qk0UUtou/SUiKMgULwGwmpdo9mYzmmM3+EJUL0ma9B4Lt9KPhAjGhHPFgxVKvVh4vLWyMoh0dz6+tCoWTnR49VpOO7jbHIULpT05zYOPWl5DEuzppYTuvw7aGHw8plf3t5jKIYS5rsFUdwIXRx+7pY/veGlS2QuxmuOTXkq1wGXZUyawYYHf3zYnssLGrzp8DZVQS37ES9Y2vN3TTa0HHM9xGttdpdP4lnCaz1p+oFuSWYLDGKkvsh7vquz9V2boJpr1S025l31mlZorksYszvn6kgfMXmR0fR8mRypUJZQxJ7MMrOL/BWZ3yQRW2W9HB/5wY2t9AjVAPSDec3WploQKv6AKsP+6Yyhf4gRkGxWtnNibmUwBf54hgs5qHtjmqN2rUzCdzHfU1HWa0/RDH0FstMsHHVbQ2KYVV0H2wx8hBIfZuNeXodpz46PEydkQNVOtlHpNN3FnWo="
