language: php

php: '5.6'
php: '7.0'

branches:
  only:
    - master

before_script:
    #@link https://github.com/Automattic/_s/blob/master/.travis.yml
    - export SNIFFS_DIR=/tmp/sniffs
    - composer install --dev
    - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
    - vendor/bin/phpcs --config-set installed_paths $SNIFFS_DIR
    # check javascript
    - npm install -g jscs
    # @link http://jshint.com/docs/
    - npm install -g jshint
    # Pull in the WP Core jshint rules.
    - wget https://develop.svn.wordpress.org/trunk/.jshintrc
script:
    # Search for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - jshint .
    - find . components/ -name "*.php" -maxdepth 1 -exec ./vendor/bin/phpcs -p -s -v {} --standard=wordpress \;
    - find . components/ -name "*.css" -maxdepth 1 -exec ./vendor/bin/phpcs -p -s -v {} --standard=wordpress \;

after_success:
    - set -e::;
    #Only Push origin
    - if [[ "false" != "$TRAVIS_PULL_REQUEST" ]]; then echo "Not deploying pull requests." ; exit ; fi
    #only master branch
    - if [[ "master" != "$TRAVIS_BRANCH" ]]; then echo "Not on the 'master' branch." ; exit ; fi
    #fetch temporary origin
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch
    #make pre-lerease branch and remove for development tools.
    - git checkout -b pre-release remotes/origin/master
    - git rm -rf stylus
    - git rm -fr git-hooks
    - git rm -f .gitignore
    - git rm -f .travis.yml
    - git rm -f README.md
    - git rm -f package.json
    - git rm -f style.css.map
    - git rm -f editor-style.css.map
    - git rm -f fonts/icomoon.zip
    - git rm -f phpcbf-all.sh
    - git rm -f phpmd-all.sh
    - git rm -f composer.*
    - git commit -m "prepare release"
    #marge release for deployment autumnsky.sakura.ne.jp
    - git checkout -b release remotes/origin/release
    - git merge pre-release -m "Travis build release $TRAVIS_COMMIT"
    - git push "https://${GH_TOKEN}@${GH_REF}" release > /dev/null 2>&1

env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=autumnsky64@gmail.com
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=autumnsky64@gmail.com
  - GH_REF: github.com/akiya64/shirohanada.git
  - secure: "NC9ILd4VHHiy9pgdHtCzGXcGd1xVwV0iJNrlBSaZrrcQKADswknS0cH2ICVU5MSWhKtqAf5LO8kBlLhlZzWsGKe3MpKHbvJvwoWaglOao76vTurL6zN9Zc//Ju7yKw2HHlLQ9lvT5mw95xq9g3xfv2t6zbtDeAH1CmMDzbAWR5+cYfu5ZK64YfD6iQFH++3CkbbVkTK2dpcdyC5XUrDUH1SQxDUI7oselloVNrNYNEzQO7aIbgzzlVYNDbEeNqXSFVoiFpt+oX9U5CblhXdtofXRukDTdIQ0yj6FxJSFLINi4yGckTzLGLbokX5Zmy6MpWfJ53JCexIEDmF4mW3MbPpnn79arbS6tqSPeqOCkcnOtd/B6sVToRV3vC25gBLBv3OYgrR2PsKCmNLEzPbRQPJbtECO2I8/CmUdshZlnq6y6XHGMpH4DbDem0HDsc+TYUzpE1sCpEqKBC8a9W61BrV5sQQAp1gi17565kOcWcJjqkJKUFg8OVctkXzdYnXJRkzowGffGHy7eAJRqmGWrzTiZlUsECCwQu1qPV0HLO97RY/QoDqqT6GU5sJP8VKES2Sil+Rewy5c01N/NhXkcdya9dBDBx3Onr2x285V4yT9mzlpvVP9bj6/cuNI8VcTn1zVsp6te1xs0JVOYJbxk+D3USXR8wNTLcaO2BRhfFE="
